version: '2'
services:
    queenbeer-app:
        image: queenbeer
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://queenbeer-mysql:3306/queenbeer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://queenbeer-elasticsearch:9200
        ports:
            - 8080:8080
    queenbeer-mysql:
        extends:
            file: mysql.yml
            service: queenbeer-mysql
    queenbeer-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: queenbeer-elasticsearch
